import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { PrimeReactProvider } from 'primereact/api';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.css';

import Header from "./components/Header/Header";
import Notifier from "./components/Notifier/Notifier";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeReactProvider>
          <Notifier/>
          <main>
            <Header/>
            {children}
          </main>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
